# Generated by Django 4.1.6 on 2023-05-02 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nis


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('firstname', models.CharField(default='SOME STRING', max_length=255)),
                ('lastname', models.CharField(default='SOME STRING', max_length=255)),
                ('dob', models.DateField(default=nis.get_default_domain)),
                ('phone', models.IntegerField(default=0)),
                ('address', models.CharField(default='SOME STRING', max_length=255)),
                ('city', models.CharField(default='SOME STRING', max_length=255)),
                ('country', models.CharField(default='SOME STRING', max_length=255)),
                ('zipCode', models.CharField(default='SOME STRING', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
