# Generated by Django 4.1.6 on 2023-05-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SmartPhones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=255)),
                ('BrandName', models.CharField(max_length=255)),
                ('ReleasedDate', models.DateField()),
                ('AverageCost', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Image', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SmartWatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=255)),
                ('BrandName', models.CharField(max_length=255)),
                ('ReleasedDate', models.DateField()),
                ('AverageCost', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Image', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Televisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=255)),
                ('BrandName', models.CharField(max_length=255)),
                ('ReleasedDate', models.DateField()),
                ('AverageCost', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Image', models.CharField(max_length=2000)),
            ],
        ),
    ]
